### ISSUE TITLE
Build a debug version of yolo_cpp_dll

### ISSUE THREAD

**Issue by SportsmanLee** [AlexeyAB/darknet#134]
Hi,

I'm developing an MFC application to use yolo to detect objects.
When I run my app in debug mode, it crashes after Detector::detect() returns. Maybe it's because I'm using release version of yolo_cpp_dll in a debug version of app?

And now I'm trying to configure yolo_cpp_dll(_no_gpu).sln to build a debug version of yolo_cpp_dll.
But I find that it only generates yolo_cpp_dll.dll, and never create yolo_cpp_dll.lib no matter how I configure it.

Could someone help me build the .lib file?
Thanks.

**Comment by AlexeyAB** [comment]
Hi,

You should use the same Multithreaded Runtime library both in DLL and your Application that uses dll. In both `Multi-threaded DLL (/MD)` or `Multi-threaded debug DLL (/MDd)`.

Your question is related to this: https://github.com/AlexeyAB/darknet/issues/113#issuecomment-312047304

> You use Debug mode for console application (exe), that uses **Debug** Multithreaded Runtime library. But DLL uses release Multithreaded Runtime library.
> 
> 1. You should use the same **release** Runtime library both for DLL and EXE.  So you should set in the **yolo-console-dll**:
> (right click on project) -> properties  ->  `C/C++ -> Code generation -> Run Time library -> Multi-threaded DLL (/MD)`
> 
> 2. You should compile DLL only in Release mode.
> 
> Also you can read: https://stackoverflow.com/questions/2322095/why-does-this-program-crash-passing-of-stdstring-between-dlls

----

> And now I'm trying to configure yolo_cpp_dll(_no_gpu).sln to build a debug version of yolo_cpp_dll.
> But I find that it only generates yolo_cpp_dll.dll, and never create yolo_cpp_dll.lib no matter how I configure it.

I fixed compile DLL in Debug mode, try to update from repo.

**Comment by SportsmanLee** [comment]
Hi,

Thanks for the reply and the reference, it helps me solve my problem.

Despite that building yolo_cpp_dll in Debug mode still don't create the .lib file, I tried to use Release version of yolo_cpp_dll.dll & yolo_cpp_dll.lib with Multi-threaded debug DLL (/MDd), which is the same with my application & dlls. And now it works well in Debug mode!

Thank you very much.

**Comment by SportsmanLee** [comment]
Hi,

There is another problem, when I built a gpu version of yolo_cpp_dll and ran yolo_console_dll.exe it reported an error about access violation inside free_network() in network.c. 
After checking the code, it crashes after `free(net.workspace);`. Thinking of releasing gpu and cpu memory issues, I tried modifying the code as below:

`	int i;
	for (i = 0; i < net.n; ++i) {
		free_layer(net.layers[i]);
	}
	free(net.layers);
	//free(net.workspace);
#ifdef GPU
	if (gpu_index >= 0) {
		cuda_free(net.workspace);
	}
	else {
		free(net.workspace);
	}
	if (*net.input_gpu) cuda_free(*net.input_gpu);
	if (*net.truth_gpu) cuda_free(*net.truth_gpu);
	if (net.input_gpu) free(net.input_gpu);
	if (net.truth_gpu) free(net.truth_gpu);
#endif`

After doing this, the access violation error will be gone.

I am wondering this is a bug, or I just did something wrong?
Could you help comment on it? Thank you.

**Comment by AlexeyAB** [comment]
@SportsmanLee Hi,

Yes, thank you, I fixed it: https://github.com/AlexeyAB/darknet/commit/576dbe12e64697f10aaa15f6ef23e0a3d5eea5b5

**Comment by SportsmanLee** [comment]
Hi @AlexeyAB ,

Okay, thank you for the fix and your project!
Close this issue.

**Comment by mypython3** [comment]
> Hi,
> 
> I'm developing an MFC application to use yolo to detect objects.
> When I run my app in debug mode, it crashes after Detector::detect() returns. Maybe it's because I'm using release version of yolo_cpp_dll in a debug version of app?
> 
> And now I'm trying to configure yolo_cpp_dll(_no_gpu).sln to build a debug version of yolo_cpp_dll.
> But I find that it only generates yolo_cpp_dll.dll, and never create yolo_cpp_dll.lib no matter how I configure it.
> 
> Could someone help me build the .lib file?
> Thanks.



> Hi,
> 
> I'm developing an MFC application to use yolo to detect objects.
> When I run my app in debug mode, it crashes after Detector::detect() returns. Maybe it's because I'm using release version of yolo_cpp_dll in a debug version of app?
> 
> And now I'm trying to configure yolo_cpp_dll(_no_gpu).sln to build a debug version of yolo_cpp_dll.
> But I find that it only generates yolo_cpp_dll.dll, and never create yolo_cpp_dll.lib no matter how I configure it.
> 
> Could someone help me build the .lib file?
> Thanks.

Hi sir .When I do a graphical interface for yolo in MFC ，encounter this:
Exception thrown by '0x000007FEE6FEEE6B(ucrtbased.dll) (located in YOLO3Test.exe): 0xC0000005: An access violation occurred while reading position 0xFFFFFFFFFFFFFFFF.
