### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by SouradipBh** [AlexeyAB/darknet#3080]
Hi, AlexeyAB,
darknet.exe detector train data/obj.data cfg/yolo-obj.cfg darknet53.conv.74
At the time of running it, i faced a problem.It shows an error.
The error is : 
                   CUDA status Error: file ..\..\src\dark_cuda.c : cuda_set_device() : line: 36 : build time: Apr 25 2019 - 12.07.50
                   CUDA Error: CUDA driver version is insufficient for CUDA runtime version

Can you please help me?

Error picture is  : 
![ERRROR](https://user-images.githubusercontent.com/50136603/56967057-12626380-6b7e-11e9-89da-27bd31099408.png)

That is my NVSMI picture:
![NVSMI](https://user-images.githubusercontent.com/50136603/56966918-bc8dbb80-6b7d-11e9-83fa-baa874fafdf8.png)

That is my NVCC version  :

![NVCC VERSION](https://user-images.githubusercontent.com/50136603/56966974-dcbd7a80-6b7d-11e9-93b5-f24b344a5a31.png)

I have installed some software in my computer,as follows:
OPENCV : 3.4.6-vc14_vc15
CUDA : 10.0.130_411.31_windows 10
cudnn : cudnn-10.0-windows10-x64-v7.4.2.24
Visual Studio:2015
NVIDIA GPU DRIVER : GEFORCE GT 635M - 2GB

**Comment by xiphosuser** [comment]
I’ve facing similar issue while trying to run Darknet.
Having a GTX 1060 with cudnn 7.5.
I’m also using cuda 10.0 with visual studio 2015.

Could someone please help?

Thanks

**Comment by AlexeyAB** [comment]
@SouradipBh @xiphosuser Hi,

It seems you should update your GPU driver.

* Did you have another CUDA versions on your PC?
* Try to set `Install nVidia Driver` during CUDA installation or install new GPU driver from: https://www.nvidia.ru/Download/Find.aspx?lang=en

**Comment by SouradipBh** [comment]
Thank You. @AlexeyAB

**Comment by martisaju** [comment]
@SouradipBh , @xiphosuser Hi, 

Could you solve it? I am facing the same problem and I can't solve it...
Thank you

**Comment by SouradipBh** [comment]
@martisaju  This problem will solved in at least rtx 2080 ti graphics. I will suugest you to use darknet as a darknet_no_gpu.

**Comment by vickyliuliu** [comment]
Hello, I encountered the same issue. I have CUDA 10.1 and driver 435.21 on my computer, and I checked the official website of NVIDIA and found out that they should be compatible  with each other. So I still cannot solve the problem... 
Any further suggestion? Thx
