### ISSUE TITLE
About label?

### ISSUE THREAD

**Issue by IDGate-ai** [AlexeyAB/darknet#5682]
If there some objects (ROI) in an image without labels, will this harm the performance?  i.e. Do yolo use negative mining?

**Comment by IDGate-ai** [comment]
Sorry! @AlexeyAB, I found that your paper that answer my question. In Bag of freebies section, "....In dealing with the problem of semantic distribution bias, a very important issue is that there is a problem of data imbalance between different classes, and this problem is often solved by hard negative example mining [72]or online hard example mining [67] in two-stage object detector.   But  the  example  mining  method  is  not  applicable to one-stage object detector, because this kind of detector belongs to the dense prediction architecture. Therefore Lin et  al.   [45]  proposed  focal  loss  to  deal  with  the  problem of  data  imbalance  existing  between  various  classes."

**Comment by AlexeyAB** [comment]
https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

check that each object that you want to detect is mandatory labeled in your dataset - no one object in your data set should not be without label. In the most training issues - there are wrong labels in your dataset (got labels by using some conversion script, marked with a third-party tool, ...). Always check your dataset by using: https://github.com/AlexeyAB/Yolo_mark

desirable that your training dataset include images with non-labeled objects that you do not want to detect - negative samples without bounded box (empty .txt files) - use as many images of negative samples as there are images with objects

**Comment by HYL-Dave** [comment]
1. If I want to classify 3 class objects with 10000 images, then are there 10000 negative samples (empty .txt files)? 
2. Suppose that I want detect dogs. Now there an image with two dogs. But there is only one label in this image (correct position). Does this decrease the accuracy due to miss a label?

**Comment by AlexeyAB** [comment]
1. I don't know are there or aren't, but it should be )
2. If you missed some labels - it will decrease accuracy
