### ISSUE TITLE
Issue run image classification 

### ISSUE THREAD

**Issue by SokPhanith** [AlexeyAB/darknet#7955]
Hello, First I build dakrnet framework on Jetson Nano include :
Jatpack 4.5.1 
CUDA 10.2
TensorRT 7.1
cuDNN 8.0.0
I Download pre-train image classification from [ImageNet Classification](https://pjreddie.com/darknet/imagenet/) and then run pre-train image classification like model **alexnet, darknet reference, vgg-16, extraction, darknet18, darknet19_448x448, Densenet 201, darknet53, darknet_448x448**, It still working for me. But all of model **resnet, resnext** got issue like 

- resnet18

     ./darknet classifier predict cfg/imagenet1k.data cfg/resnet18.cfg weight/resnet18.weights data/dog.jpg
 CUDA-version: 10020 (10020), cuDNN: 8.0.0, GPU count: 1  
 OpenCV version: 4.1.1
 0 : compute_capability = 530, cudnn_half = 0, GPU: NVIDIA Tegra X1 
net.optimized_memory = 0 
mini_batch = 1, batch = 1, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 Create CUDA-stream - 0 
 Create cudnn-handle 0 
conv     64       7 x 7/ 2    256 x 256 x   3 ->  128 x 128 x  64 0.308 BF
   1 max                2x 2/ 2    128 x 128 x  64 ->   64 x  64 x  64 0.001 BF
   2 conv     64       3 x 3/ 1     64 x  64 x  64 ->   64 x  64 x  64 0.302 BF
   3 conv     64       3 x 3/ 1     64 x  64 x  64 ->   64 x  64 x  64 0.302 BF
   4 Shortcut Layer: 1,  wt = 0, wn = 0, outputs:  64 x  64 x  64 0.000 BF
   5 conv     64       3 x 3/ 1     64 x  64 x  64 ->   64 x  64 x  64 0.302 BF
   6 conv     64       3 x 3/ 1     64 x  64 x  64 ->   64 x  64 x  64 0.302 BF
   7 Shortcut Layer: 4,  wt = 0, wn = 0, outputs:  64 x  64 x  64 0.000 BF
   8 conv    128       3 x 3/ 2     64 x  64 x  64 ->   32 x  32 x 128 0.151 BF
   9 conv    128       3 x 3/ 1     32 x  32 x 128 ->   32 x  32 x 128 0.302 BF
  10 Shortcut Layer: 7,  wt = 0, wn = 0, outputs:  32 x  32 x 128 0.000 BF
darknet: ./src/parser.c:994: parse_shortcut: Assertion `params.w == net.layers[index].out_w && params.h == net.layers[index].out_h' failed.
Aborted (core dumped)

- resnext50
  ./darknet classifier predict cfg/imagenet1k.data cfg/resnext50.cfg weight/resnext50.weights data/dog.jpg
 CUDA-version: 10020 (10020), cuDNN: 8.0.0, GPU count: 1  
 OpenCV version: 4.1.1
 0 : compute_capability = 530, cudnn_half = 0, GPU: NVIDIA Tegra X1 
net.optimized_memory = 0 
mini_batch = 1, batch = 1, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 Create CUDA-stream - 0 
 Create cudnn-handle 0 
conv     64       7 x 7/ 2    256 x 256 x   3 ->  128 x 128 x  64 0.308 BF
   1 max                2x 2/ 2    128 x 128 x  64 ->   64 x  64 x  64 0.001 BF
   2 conv    128       1 x 1/ 1     64 x  64 x  64 ->   64 x  64 x 128 0.067 BF
   3 conv    128/  32  3 x 3/ 1     64 x  64 x 128 ->   64 x  64 x 128 0.038 BF
   4 conv    256       1 x 1/ 1     64 x  64 x 128 ->   64 x  64 x 256 0.268 BF
   5 Shortcut Layer: 1,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
 (  64 x  64 x 256) + (  64 x  64 x  64) 
   6 conv    128       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 128 0.268 BF
   7 conv    128/  32  3 x 3/ 1     64 x  64 x 128 ->   64 x  64 x 128 0.038 BF
   8 conv    256       1 x 1/ 1     64 x  64 x 128 ->   64 x  64 x 256 0.268 BF
   9 Shortcut Layer: 5,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  10 conv    128       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 128 0.268 BF
  11 conv    128/  32  3 x 3/ 1     64 x  64 x 128 ->   64 x  64 x 128 0.038 BF
  12 conv    256       1 x 1/ 1     64 x  64 x 128 ->   64 x  64 x 256 0.268 BF
  13 Shortcut Layer: 9,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  14 conv    256       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 256 0.537 BF
  15 conv    256/  32  3 x 3/ 2     64 x  64 x 256 ->   32 x  32 x 256 0.038 BF
  16 conv    512       1 x 1/ 1     32 x  32 x 256 ->   32 x  32 x 512 0.268 BF
  17 Shortcut Layer: 13,  wt = 0, wn = 0, outputs:  32 x  32 x 512 0.001 BF
darknet: ./src/parser.c:994: parse_shortcut: Assertion `params.w == net.layers[index].out_w && params.h == net.layers[index].out_h' failed.
Aborted (core dumped)

**Comment by lsd1994** [comment]
img size wrong

**Comment by linyib** [comment]
hello，is solved？

**Comment by He32100** [comment]
> img size wrong

Hello, I also encountered the same problem, but after modifying the image size, it still couldn't solve the problem. Have you solved this problem yet

**Comment by stephanecharette** [comment]
Please use the new repo:  https://github.com/hank-ai/darknet

**Comment by He32100** [comment]
> Please use the new repo: https://github.com/hank-ai/darknet

Hello, I reinstalled darknet using this new repo you gave and tried again, but still get similar errors. Is there something wrong with my resnext50.cfg or resnext50.weights file? These two files are downloaded from the url--https://pjreddie.com/darknet/imagenet/




./darknet classifier predict cfg/imagenet1k.data cfg/resnext50.cfg resnext50.weights data/dog.jpg
 GPU isn't used 
OpenCV is disabled - image loading and data augmentation will be slow
mini_batch = 1, batch = 1, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 conv     64       7 x 7/ 2    256 x 256 x   3 ->  128 x 128 x  64 0.308 BF
   1 max                2x 2/ 2    128 x 128 x  64 ->   64 x  64 x  64 0.001 BF
   2 conv    128       1 x 1/ 1     64 x  64 x  64 ->   64 x  64 x 128 0.067 BF
   3 conv    128/  32  3 x 3/ 1     64 x  64 x 128 ->   64 x  64 x 128 0.038 BF
   4 conv    256       1 x 1/ 1     64 x  64 x 128 ->   64 x  64 x 256 0.268 BF
   5 Shortcut Layer: 1,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
 (  64 x  64 x 256) + (  64 x  64 x  64) 
   6 conv    128       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 128 0.268 BF
   7 conv    128/  32  3 x 3/ 1     64 x  64 x 128 ->   64 x  64 x 128 0.038 BF
   8 conv    256       1 x 1/ 1     64 x  64 x 128 ->   64 x  64 x 256 0.268 BF
   9 Shortcut Layer: 5,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  10 conv    128       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 128 0.268 BF
  11 conv    128/  32  3 x 3/ 1     64 x  64 x 128 ->   64 x  64 x 128 0.038 BF
  12 conv    256       1 x 1/ 1     64 x  64 x 128 ->   64 x  64 x 256 0.268 BF
  13 Shortcut Layer: 9,  wt = 0, wn = 0, outputs:  64 x  64 x 256 0.001 BF
  14 conv    256       1 x 1/ 1     64 x  64 x 256 ->   64 x  64 x 256 0.537 BF
  15 conv    256/  32  3 x 3/ 2     64 x  64 x 256 ->   32 x  32 x 256 0.038 BF
  16 conv    512       1 x 1/ 1     32 x  32 x 256 ->   32 x  32 x 512 0.268 BF
  17 Shortcut Layer: 13,  wt = 0, wn = 0, outputs:  32 x  32 x 512 0.001 BF
darknet: ./src/parser.c:1028: parse_shortcut: Assertion `params.w == net.layers[index].out_w && params.h == net.layers[index].out_h' failed.

* * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* A fatal error has been detected.  Darknet will now exit.
* Error location: ./src/darknet.c, darknet_signal_handler(), line #440
* Error message:  signal handler invoked for signal #6 (Aborted)
* * * * * * * * * * * * * * * * * * * * * * * * * * * * *
backtrace (14 entries):
1/14: ./darknet(log_backtrace+0x38) [0x562112d38108]
2/14: ./darknet(darknet_fatal_error+0x19d) [0x562112d3834d]
3/14: /lib/x86_64-linux-gnu/libc.so.6(+0x430c0) [0x7fe7478e30c0]
4/14: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7fe7478e303b]
5/14: /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7fe7478c2859]
6/14: /lib/x86_64-linux-gnu/libc.so.6(+0x22729) [0x7fe7478c2729]
7/14: /lib/x86_64-linux-gnu/libc.so.6(+0x34006) [0x7fe7478d4006]
8/14: ./darknet(parse_shortcut+0x7f6) [0x562112da1266]
9/14: ./darknet(parse_network_cfg_custom+0x4022) [0x562112da6f62]
10/14: ./darknet(predict_classifier+0x55) [0x562112dcb3c5]
11/14: ./darknet(run_classifier+0x6ea) [0x562112dcc91a]
12/14: ./darknet(main+0x55b) [0x562112d2d0db]
13/14: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fe7478c40b3]
14/14: ./darknet(_start+0x2e) [0x562112d2d44e]
Aborted (core dumped)
